---
- name: Install xinetd for cups-lpd
  block:
    - name: Install xinetd for cups-lpd
      ansible.builtin.package:
        name: xinetd
        state: present

    - name: Create cups-lpd user - {{ cups_lpd_user }}
      ansible.builtin.user:
        name: "{{ cups_lpd_user }}"
        append: true
        groups: "{{ cups_admin_group }}"

    - name: Copying over cups-lpd using cups-lpd.j2 template
      ansible.builtin.template:
        src: "cups-lpd.j2"
        dest: "{{ cups_xinetd_location }}/cups-lpd"
        owner: root
        group: root
        mode: "0644"
