---
<<<<<<< HEAD
- name: Install CUPS
  package:
    name: "{{ cups_packages_to_install }}"
    state: present

- name: Ensure lpadmin group exists 
  group:
    name: "{{ cups_admin_group }}"
    state: present

- name: Ensure lpadmin permissions
  lineinfile:
    path: "{{ item }}"
    regexp: "^SystemGroup"
    line: "SystemGroup {{ cups_admin_grp }}"
  with_items:
    - "/etc/cups/cupsd.conf"
    - "/etc/cups/cups-files.conf"
=======
- name: Apt Packages Install CUPS
  include: apt_cups_install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Yum Packages Install CUPS
  include: yum_cups_install.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Adds lpadmin group
  group:
    name: lpadmin
    state: present
>>>>>>> pr9/master

- name: Add accounts to lpadmin group (CUPS admin)
  user:
    name: "{{ item }}"
    append: yes
    groups: "{{ cups_admin_group }}"
  with_items:
    - "{{ cups_lpadmin_users }}"

- name: Include - CUPS-LPD
  include: cups_install_lpd.yml
<<<<<<< HEAD
  when: cups_lpd
=======
  when: 
    - (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
    - cups_lpd
...
>>>>>>> pr9/master
