---
- name: Install CUPS
  package:
    name: "{{ item }}"
    state: present
    with_items:
      - "{{ cups_packages_to_install }}"

- name: Ensure lpadmin group exists 
  group:
    name: "{{ cups_admin_group }}"
    state: present

- name: Ensure lpadmin permissions
  lineinfile:
    path: "{{ item }}"
    regexp: "^SystemGroup"
    line: "SystemGroup {{ cups_admin_group }}"
  with_items:
    - "/etc/cups/cupsd.conf"
    - "/etc/cups/cups-files.conf"

- name: Add accounts to lpadmin group (CUPS admin)
  user:
    name: "{{ item }}"
    append: yes
    groups: "{{ cups_admin_group }}"
  with_items:
    - "{{ cups_lpadmin_users }}"

- name: Include - CUPS-LPD
  ansible.builtin.include_tasks: cups_install_lpd.yml
  when: cups_lpd
