---
- name: Creating CUPS tmp location {{ cups_tmp_location }}
  ansible.builtin.file:
    path: "{{ cups_tmp_location }}"
    recurse: true
    state: directory

- name: Creating {{ cups_ppd_shared_location }}
  ansible.builtin.file:
    path: "{{ cups_ppd_shared_location }}"
    recurse: true
    state: directory

- block:
    - name: Add OpenPrinting APT Key
      ansible.builtin.apt_key:
        id: "{{ cups_openprinting_apt_key_id }}"
        keyserver: "{{ cups_openprinting_key_server }}"

    - name: Add OpenPrinting Package repo
      ansible.builtin.apt_repository:
        repo: "{{ cups_openprinting_repo }}"
        state: present
        update_cache: true
  when: cups_openprinting_apt_required is defined and cups_openprinting_apt_required == True

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    # upgrade: safe

# If the output is none or the command failed to find "install ok installed" then it means the package wasn't installed beforehand
- name: Check and register if expect related packages are already installed.
  ansible.builtin.command: dpkg -s {{ item }} | grep 'install ok installed'
  register: cups_expect_packages_already_installed
  with_items:
    - "{{ cups_expect_packages }}"
  changed_when: False
  failed_when: False

- name: Ensure expect related packages are installed to guide us through CUPS installation.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  register: cups_expect_install
  with_items:
    - "{{ cups_expect_packages }}"