---
- block:
    - name: Include Debian / Ubuntu vars
      ansible.builtin.include_vars: debian.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Include Red Hat / CentOS vars
      ansible.builtin.include_vars: redhat.yml
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Include Suse vars
      ansible.builtin.include_vars: suse.yml
      when: ansible_distribution == 'SLES' or ansible_distribution == 'openSUSE Leap'

    - name: Include - Pre-Install steps
      ansible.builtin.import_tasks: cups_pre_install_debian.yml
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Include - Pre-Install steps
      ansible.builtin.import_tasks: cups_pre_install_suse.yml
      become: true
      when: ansible_facts['os_family'] == 'Suse'

    - name: Include - Pre-Install steps
      ansible.builtin.import_tasks: cups_pre_install_rpm.yml
      become: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Include - Install CUPS
      ansible.builtin.import_tasks: cups_install.yml
      become: true

    - name: Include - Configure CUPS
      ansible.builtin.import_tasks: cups_configure.yml
      become: true

    - name: Include - Install PPDs.
      ansible.builtin.import_tasks: ppd_install.yml
      become: true

    - name: Include - Uninstall any defined printers and install any printers and classes defined.
      ansible.builtin.import_tasks: printer_and_class_install.yml
      become: true

  always:
    - name: Include - CUPS Cleanup
      ansible.builtin.import_tasks: cups_cleanup.yml
      become: true
